@startuml class_diagram
package com.N8V37{
    package com.N8V37.Ressources{
        abstract material
        class library
        TD --|> material        
        cours --|> material
        TP --|> material
        evaluation --|> test
        quizz --|> test
        test --o "0..*" question 
        test o-- library
        material o-- library
        
    }


    package com.N8V37.Roles{
        supervisor --> teacher
        teacher --> member
    
    }
    package com.N8V37.Features{
        class schedule
        class FAQ
        namespace gfx{
            class dummy
            } 
        
        
    }
    member --# schedule
    class Main
    class module{
        + module_id : int
    }
    module "1..*" -- library : extracts >
    class member{
        - member_id : int
        - member_lastname : string
        - member_firstname : string
        - wallet : List<String>
        - Login : string
        - password : string 
        - Schedule : schedule      
        + getinfo()
        + setinfo()
        + destruct()
        + editFAQ()
        + editschedule()
    }
    class teacher {
        + addcourse()
        + delcourse()
        + editcourse()
        + addmember()
        + delmember()
        
    }
    class supervisor{
        + setRole()
    }
    class test{
        - test_id : int
        - length : int
        - question : question
        - title : string
        - answer : file
        + send_answer()

    }
    class evaluation{
        + period : int
        - setTime()
    }
    class question{
        + question_id : int
        + question_weight : int
        + edit()

    }
}
@enduml
